// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{PROVERS_ELF, PROVERS_ID};
use methods::{INSERT_ELF,INSERT_ID};
use risc0_zkvm::{default_prover, ExecutorEnv, get_version};
use tracing_subscriber;
fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    let input: u32 = 15;
    let add : u32 = 15;
    let env = ExecutorEnv::builder()
        .write(&input).unwrap()
        .write(&add).unwrap()
        .segment_limit_po2(18)
        .build()
        .unwrap();

    let prover = default_prover();
    let prove_info = prover
        .prove(env, PROVERS_ELF)
        .unwrap();
    let receipt = prove_info.receipt;
    let output: u32 = receipt.journal.decode().unwrap();

    let total_cycles=prove_info.stats.total_cycles;

    println!("output : {}",output);
    println!("total cycles : {}",total_cycles);
    receipt
        .verify(PROVERS_ID)
        .unwrap();
}
