syntax = "proto3";
package sequencer;

service RootAnchoring {
  rpc SubmitRoot (RootSubmission) returns (Response);
  rpc UpdateRoot (RootUpdate) returns (Response);
}

message RootSubmission {
  bytes certificate_root = 1;
  bytes signature = 2;
  bytes public_key = 3;  
}

message RootUpdate {
  bytes old_certificate_root = 1;
  bytes new_certificate_root = 2;
  bytes signature = 3;
  bytes public_key = 4;  
}


enum SequencerStatus {
  UNKNOWN = 0;
  ACCEPTED = 1;
  INVALID_SIGNATURE = 2;
  INTERNAL_ERROR = 3;
}

message Response {
  SequencerStatus status = 1;
  uint64 sequence_number = 2; 
  string error_details = 3;   
}